config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           sign_up: 'register' },
             controllers: { sessions: 'users/sessions',
                            passwords: 'users/passwords',
                            registrations: 'users/registrations',
                            unlocks: 'users/unlocks' }

  get 'users/invitation' => 'users/user_invitations#show', as: :new_user_invitation
  post 'users/invitation/accept' => 'users/user_invitations#accept', as: :accept_user_invitation
  resources :users, only: [:index, :show, :edit, :update] do
    get 'accounts' => 'users#accounts'
    get 'user_invitations' => 'users#user_invitations'
  end
  namespace :admin do
    resources :accounts, except: [:destroy] do
      resources :invoices, only: [:index]
      resources :user_invitations
      get 'cancel' => 'accounts#confirm_cancel'
      patch 'cancel' => 'accounts#cancel'
      get 'events' => 'accounts#events'
      get 'restore' => 'accounts#confirm_restore'
      patch 'restore' => 'accounts#restore'
      get 'users' => 'accounts#users'
    end
    resources :cancellation_categories, except: [:destroy] do
      resources :cancellation_reasons, except: [:destroy]
    end
    resources :invoices, only: [:index, :show]
    resources :plans do
      get 'accounts' => 'plans#accounts'
    end
    resources :users do
      get 'accounts' => 'users#accounts'
      get 'user_invitations' => 'users#user_invitations'
    end
    get 'events' => 'dashboard#events'
    get 'jobs' => 'dashboard#jobs'
    get 'user_invitations' => 'user_invitations#index'
    root to: 'dashboard#index'
  end

  get 'pricing' => 'marketing#pricing'
  get 'signup/:plan_id' => 'marketing#signup', as: :signup
  post 'signup' => 'marketing#register', as: :register

  scope ':path' do
    namespace :settings do
      resource :account, only: [:show, :edit, :update]
      resource :card, only: [:show, :edit, :update]
      resources :invoices, only: [:index, :show]
      resource :plan, only: [:show, :update, :destroy] do
        get 'cancel'
        patch 'pause'
        get ':id' => 'plans#edit', as: :edit
      end
      resources :user_permissions, except: [:create, :new]
      resources :user_invitations
      root to: 'dashboard#index'
    end
    root to: 'dashboard#index', as: :tenant_root
  end

  root to: 'marketing#index'
end

app/controllers/admin/plans_controller.rb
# Encoding: utf-8

# Copyright (c) 2014-2015, Richard Buggy <rich@buggy.id.au>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Provides plans administration in the admin section
class Admin::PlansController < Admin::ApplicationController
  add_breadcrumb 'Plans', :admin_plans_path

  before_action :find_plan, only: [:account,
                                   :destroy,
                                   :edit,
                                   :show,
                                   :update,
                                   :accounts,
                                   :paused_plans]

  authorize_resource

  def index
    @plans = Plan.page(params[:page])
  end

  def accounts
    add_breadcrumb 'Edit', admin_plan_accounts_path(@plan)
    @accounts =
      Account.includes(:plan).where('plan_id = ? or paused_plan_id = ?', @plan.id, @plan.id).page(params[:page])
  end

  def create
    @plan = Plan.new(plans_create_params)
    if @plan.save
      StripePlanCreateJob.perform_later @plan.id
      AppEvent.success("Created plan #{@plan}", nil, current_user)
      logger.info { "Plan '#{@plan}' created - #{admin_plan_url(@plan)}" }
      redirect_to admin_plan_path(@plan),
                  notice: 'Plan was successfully created.'
    else
      add_breadcrumb 'New', new_admin_plan_path
      logger.debug { "Plan create failed #{@plan}" }
      render 'new'
    end
  end

  def edit
    add_breadcrumb 'Edit', edit_admin_plan_path(@plan)
  end

  def new
    add_breadcrumb 'New', new_admin_plan_path
    @plan = Plan.new
  end

  def show
  end

  def update
    if @plan.update_attributes(plans_update_params)
      StripePlanUpdateJob.perform_later @plan.id
      logger.info { "Plan '#{@plan}' updated - #{admin_plan_url(@plan)}" }
      AppEvent.success("Updated plan #{@plan}", nil, current_user)
      redirect_to admin_plan_path(@plan),
                  notice: 'Plan was successfully updated.'
    else
      add_breadcrumb 'Edit', edit_admin_plan_path(@plan)
      logger.debug { "Plan update failed #{@plan.inspect}" }
      render 'edit'
    end
  end

  def destroy
    if @plan.destroy
      StripePlanDeleteJob.perform_later(@plan.stripe_id)
      AppEvent.info("Deleted plan #{@plan}", nil, current_user)
      logger.info { "Plan '#{@plan}' destroyed - #{admin_plan_url(@plan)}" }
      redirect_to admin_plans_path,
                  notice: 'Plan was successfully removed.'
    else
      logger.debug { "Plan destroy failed #{@plan.inspect}" }
      redirect_to admin_plan_path(@plan),
                  alert: 'Plan could not be removed.'
    end
  end

  private

  def find_plan
    @plan = Plan.find(params[:plan_id] || params[:id])
    add_breadcrumb @plan, admin_plan_path(@plan)
  end

  def plans_create_params
    params.require(:plan).permit(:active,
                                 :allow_custom_path,
                                 :allow_hostname,
                                 :allow_subdomain,
                                 :amount,
                                 :currency,
                                 :interval,
                                 :interval_count,
                                 :label,
                                 :max_users,
                                 :name,
                                 :paused_plan_id,
                                 :public,
                                 :require_card_upfront,
                                 :statement_description,
                                 :stripe_id,
                                 :trial_period_days)
  end

  def plans_update_params
    params.require(:plan).permit(:active,
                                 :allow_custom_path,
                                 :allow_hostname,
                                 :allow_subdomain,
                                 :max_users,
                                 :label,
                                 :name,
                                 :paused_plan_id,
                                 :public,
                                 :require_card_upfront,
                                 :statement_description)
  end

  def set_sidebar_item
    @sidebar_item = :plans
  end
end

app/controllers/settings/accounts_controller.rb
# Encoding: utf-8

# Copyright (c) 2014-2015, Richard Buggy <rich@buggy.id.au>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Allows the account admin to manage account details in the settings
class Settings::AccountsController < Settings::ApplicationController
  add_breadcrumb 'Account', :settings_account_path

  authorize_resource

  def home
  end

  def edit
    add_breadcrumb 'Edit', edit_settings_account_path
  end

  def show
  end

  def update
    if @account.update_attributes(accounts_params)
      StripeAccountUpdateJob.perform_later @account.id
      AppEvent.success('Updated account details', current_account, current_user)
      logger.info { "Account '#{@account}' updated - #{admin_account_url(@account)}" }
      redirect_to settings_root_path, notice: 'Account was successfully updated.'
    else
      add_breadcrumb 'Edit', edit_settings_account_path
      logger.debug { "Account update failed #{@account.inspect}" }
      render 'edit'
    end
  end

  private

  def set_sidebar_item
    @sidebar_item = :settings_account
  end

  def accounts_params
    params.require(:account).permit(:address_city,
                                    :address_country,
                                    :address_line1,
                                    :address_line2,
                                    :address_state,
                                    :address_zip,
                                    :company_name,
                                    :email,
                                    :hostname,
                                    :subdomain)
  end
end

app/controllers/settings/application_controller.rb
# Encoding: utf-8

# Copyright (c) 2014-2015, Richard Buggy <rich@buggy.id.au>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Base class for all settings section controllers that provides common functionality
class Settings::ApplicationController < ApplicationController
  add_breadcrumb 'Settings', :settings_root_path

  before_action :find_account

  # Return the ability model. It needs to know about the user and the account.
  def current_ability
    Ability.new(current_user, current_account, :settings)
  end

  def set_sidebar_item
    @sidebar_item = :settings
  end

  def find_account
    @account = current_account
  end
end

app/controllers/settings/cards_controller.rb
# Encoding: utf-8

# Copyright (c) 2014-2015, Richard Buggy <rich@buggy.id.au>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Allows the account admin to manage cards in the settings
class Settings::CardsController < Settings::ApplicationController
  add_breadcrumb 'Credit Card', :settings_card_path

  before_action :find_account, only: [:show, :edit, :update]

  before_action do
    authorize!(params[:action], @account || Account)
  end

  def show
  end

  def edit
    add_breadcrumb 'Edit', edit_settings_card_path
    @account.card_token = nil
  end

  def update
    if @account.update_attributes(accounts_params)
      StripeAccountUpdateJob.perform_later @account.id
      AppEvent.success('Updated credit card', current_account, current_user)
      logger.info { "Card for '#{@account}' updated - #{admin_account_url(@account)}" }
      redirect_to settings_root_path,
                  notice: 'Credit card was successfully updated.'
    else
      add_breadcrumb 'Edit', edit_settings_card_path
      @account.card_token = nil
      logger.debug { "Card update failed #{@account.inspect}" }
      render 'edit'
    end
  end

  private

  def set_sidebar_item
    @sidebar_item = :settings_card
  end

  def find_account
    @account = current_account
  end

  def accounts_params
    params.require(:account).permit(:card_token)
  end
end

app/views/settings/plans/cancel.html.erb
<%
content_for(:page_title, 'Cancel Account')
content_for(:page_heading, 'Cancel Account')
%>

<h2 class="text-danger">Danger Zone!!</h2>

<p>We're really sorry that you want to leave.</p>

<% if can?(:pause, @account) %>
<p>Don't need your account right now but don't really want to remove it? Why not pause your account
instead? Pausing is <%= formatted_plan_price(@account.plan.paused_plan, 'FREE') %>.</p>
<p>When you need to your account activated again just email <a href="mailto:support@railssaastemplate.com">support@railssaastemplate.com</a></p>
<p><%= link_to "Pause account", pause_settings_plan_path, class: "btn btn-success", method: :patch %></p>
<% end %>

<p>Please indicate below why you're leaving:</p>

<%= render_errors @account %>

<%= form_for [:admin, @account], url: settings_plan_path(@account), method: :delete do |f| %>

  <div id="cancellation-reason-block" class="form-group">
      <label>Cancellation Reason</label>
      <ul style="list-style: none">
          <% @cancellation_categories.each do |cancellation_category| %>
          <li>
            <%= f.radio_button(:cancellation_category_id, cancellation_category.id, class: "cancellation-category", data: { allow_message: cancellation_category.allow_message, require_message: cancellation_category.require_message }) %> <%= cancellation_category.name %>
            <ul style="list-style: none;" id="cancellation_reason_for_category_<%= cancellation_category.id%>" class="cancellation-reasons">
            <% cancellation_category.cancellation_reasons.each do |cancellation_reason| %>
                <li><%= f.radio_button(:cancellation_reason_id, cancellation_reason.id, class: "cancellation-reason", data: { allow_message: cancellation_reason.allow_message, require_message: cancellation_reason.require_message }) %> <%= cancellation_reason.name %></li>
            <% end %>
            </ul>
          </li>
          <% end %>
      </ul>
  </div>

  <div id="cancellation-message-block" class="form-group">
    <%= f.label :cancellation_message %>
    <%= f.text_field :cancellation_message, class: "form-control" %>
  </div>

  <%= f.submit "Cancel Account", class: "btn btn-danger" %>
  <%= link_to "Keep account", settings_account_path, class: "btn btn-primary" %>
<% end %>

<% content_for :footer do %>
<script type="text/javascript">
    $(function () {
        // Hide cancellation message and all of the reasons
        $("#cancellation-message-block").css("display", "none");
        $(".cancellation-reasons").css("display", "none");
        // When someone clicks on a category
        $(".cancellation-category").on("click", function() {
          // Hide and uncheck all reasons then show the reasons for this category only
          $(".cancellation-reasons").css("display", "none");
          $(".cancellation-reason").prop("checked", false);
          $("#cancellation_reason_for_category_" + $(this).val()).css("display", "block");
          // Figure out if we should be displaying the message box
          var display = "none";
          if ($(this).data('allow-message') || $(this).data('require-message')) {
            display = "block";
          }
          $("#cancellation-message-block").css("display", display);
        });
        // When someone clicks on a reason
        $(".cancellation-reason").on("click", function() {
          // Figure out if we should be displaying the message box
          var display = "none";
          if ($(this).data('allow-message') || $(this).data('require-message')) {
            display = "block";
          }
          $("#cancellation-message-block").css("display", display);
        });
    });
</script>
<% end %>

app/views/settings/plans/edit.html.erb
<%
content_for(:page_title, 'Change Plan')
content_for(:page_heading, 'Change Plan')
%>

<%= render_errors @account %>

<%= form_for [:settings, @account], url: settings_plan_path, method: :patch do |f| %>
  <h2>Confirm Plan Change</h2>
  <p>Put a nice message here :).</p>
  <%= f.hidden_field :plan_id %>
  <%= f.submit "Change Plan", class: "btn btn-primary" %>
  <%= link_to "Discard Changes", settings_plan_path %>
<% end %>

app/views/settings/plans/show.html.erb
<%
content_for(:page_title, 'Plans')
content_for(:page_heading, 'Plans')
%>

<%= render 'shared/pricing_table', plans: @plans, account: @current_account, action: :change  %>

<div class="row">
  <div class="col-sm-12">
    <p><%= link_to "Cancel account", cancel_settings_plan_path, class: "btn btn-danger" %></p>
  </div>
</div>