config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           sign_up: 'register' },
             controllers: { sessions: 'users/sessions',
                            passwords: 'users/passwords',
                            registrations: 'users/registrations',
                            unlocks: 'users/unlocks' }

  get 'users/invitation' => 'users/user_invitations#show', as: :new_user_invitation
  post 'users/invitation/accept' => 'users/user_invitations#accept', as: :accept_user_invitation
  resources :users, only: [:index, :show, :edit, :update] do
    get 'accounts' => 'users#accounts'
    get 'user_invitations' => 'users#user_invitations'
  end
  namespace :admin do
    resources :accounts, except: [:destroy] do
      resources :invoices, only: [:index]
      resources :user_invitations
      get 'cancel' => 'accounts#confirm_cancel'
      patch 'cancel' => 'accounts#cancel'
      get 'events' => 'accounts#events'
      get 'restore' => 'accounts#confirm_restore'
      patch 'restore' => 'accounts#restore'
      get 'users' => 'accounts#users'
    end
    resources :cancellation_categories, except: [:destroy] do
      resources :cancellation_reasons, except: [:destroy]
    end
    resources :invoices, only: [:index, :show]
    resources :plans do
      get 'accounts' => 'plans#accounts'
    end
    resources :users do
      get 'accounts' => 'users#accounts'
      get 'user_invitations' => 'users#user_invitations'
    end
    get 'events' => 'dashboard#events'
    get 'jobs' => 'dashboard#jobs'
    get 'user_invitations' => 'user_invitations#index'
    root to: 'dashboard#index'
  end

  get 'pricing' => 'marketing#pricing'
  get 'signup/:plan_id' => 'marketing#signup', as: :signup
  post 'signup' => 'marketing#register', as: :register

  scope ':path' do
    namespace :settings do
      resource :account, only: [:show, :edit, :update]
      resource :card, only: [:show, :edit, :update]
      resources :invoices, only: [:index, :show]
      resource :plan, only: [:show, :update, :destroy] do
        get 'cancel'
        patch 'pause'
        get ':id' => 'plans#edit', as: :edit
      end
      resources :user_permissions, except: [:create, :new]
      resources :user_invitations
      root to: 'dashboard#index'
    end
    root to: 'dashboard#index', as: :tenant_root
  end

  root to: 'marketing#index'
end

app/models/invoice.rb
# Encoding: utf-8

# Copyright (c) 2014-2015, Richard Buggy <rich@buggy.id.au>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Invoice model
class Invoice < ActiveRecord::Base
  belongs_to :account

  before_validation(on: :create) do
    unless inv_number
      max_inv_number = Invoice.maximum(:inv_number)
      if max_inv_number
        self.inv_number = max_inv_number + 1
      else
        self.inv_number = 1
      end
    end
  end

  validates :account_id, presence: true
  validates :download_url, length: { maximum: 255 }
  validates :inv_number,
            numericality: { greater_than: 0, integer_only: true },
            uniqueness: true,
            presence: true
  validates :invoiced_at, presence: true
  validates :total_amount,
            numericality: true,
            presence: true
  validates :stripe_invoice_id, length: { maximum: 100 }, presence: true

  # rubocop:disable Rails/Delegate
  def to_s
    inv_number.to_s
  end
  # rubocop:enable Rails/Delegate
end

app/controllers/admin/invoices_controller.rb
# Encoding: utf-8

# Copyright (c) 2014-2015, Richard Buggy <rich@buggy.id.au>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Provides invoices administration in the admin section
class Admin::InvoicesController < Admin::ApplicationController
  before_action :find_account
  before_action :find_invoice, only: [:show]

  authorize_resource

  def index
    if @account
      @invoices = @account.invoices.page(params[:page])
      @nav_item = 'accounts'
    else
      @invoices = Invoice.page(params[:page])
    end
  end

  def show
  end

  private

  def find_account
    if params[:account_id]
      @account = Account.find(params[:account_id])
      @sidebar_item = :accounts
      add_breadcrumb 'Accounts', admin_accounts_path
      add_breadcrumb @account, admin_account_path(@account)
      add_breadcrumb 'User Invitations', admin_account_user_invitations_path(@account)
    else
      add_breadcrumb 'Invoices', :admin_invoices_path
    end
  end

  def find_invoice
    @invoice = Invoice.find(params[:invoice_id] || params[:id])
    add_breadcrumb @invoice, admin_invoice_path(@invoice)
  end

  def set_sidebar_item
    @sidebar_item = :invoices
  end
end

app/controllers/settings/invoices_controller.rb
# Encoding: utf-8

# Copyright (c) 2014-2015, Richard Buggy <rich@buggy.id.au>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Allows the account admin to view invoices in the settings
class Settings::InvoicesController < Settings::ApplicationController
  add_breadcrumb 'Invoices', :settings_invoices_path

  before_action :find_invoice, only: [:show]

  authorize_resource

  def index
    @invoices = current_account.invoices.page(params[:page])
  end

  def show
    if @invoice.download_url
      redirect_to @invoice.download_url
    else
      redirect_to settings_invoices_path
    end
  end

  private

  def find_invoice
    @invoice = current_account.invoices.find(params[:id])
  end

  def set_sidebar_item
    @sidebar_item = :settings_invoices
  end
end

app/views/admin/invoices/index.html.erb
<%
content_for(:page_title, 'Invoices')
content_for(:page_heading, 'Invoices')
%>

<% if @account %>
<ul class="nav nav-pills">
  <% if can?(:index, @account) %><li><%= link_to "Account", admin_account_path(@account) %></li><% end %>
  <% if can?(:users, @account) %><li><%= link_to "Users", admin_account_users_path(@account) %></li><% end %>
  <% if can?(:index, @account) %><li><%= link_to "User Invitations", admin_account_user_invitations_path(@account) %></li><% end %>
  <li class="active"><%= link_to "Invoices", admin_account_invoices_path(@account) %></li>
  <% if can?(:events, @account) %><li><%= link_to "Events", admin_account_events_path(@account) %></li><% end %>
</ul>
<% end %>

<% if @invoices.empty? then %>
<p>No invoices found</p>
<% else %>
<table class="table table-condensed table-striped">
	<thead>
		<tr>
			<th>Inv #</th>
			<th>Account</th>
			<th>Invoiced At</th>
			<th>Paid At</th>
			<th>Amount</th>
			<th>Stripe ID</th>
		</tr>
	</thead>
	<tbody>
<% @invoices.each do |invoice| %>
		<tr>
			<td><%= link_to_if can?(:show, invoice), invoice.inv_number, admin_invoice_path(invoice) %></td>
			<td><%= link_to_if can?(:show, invoice.account), invoice.account, admin_account_path(invoice.account) %></td>
			<td><%= invoice.invoiced_at %></td>
			<td><%= invoice.paid_at %></td>
			<td><%= invoice.total_amount %></td>
                        <td><%= invoice.stripe_invoice_id %> <a href="https://dashboard.stripe.com/test/invoices/<%= invoice.stripe_invoice_id  %>"><%= fa_icon 'external-link' %></a><% if invoice.download_url %> <a href="<%= invoice.download_url %>"><%= fa_icon 'download' %></a><% end %></td>
		</tr>
<% end %>
	</tbody>
</table>
<%= paginate @invoices %>
<% end %>

app/views/admin/invoices/show.html.erb
<%
content_for(:page_title, "Invoice - #{@user_invitation}")
content_for(:page_heading, 'Invoices')
%>

<% if @account %>
<ul class="nav nav-pills">
  <% if can?(:index, @account) %><li><%= link_to "Account", admin_account_path(@account) %></li><% end %>
  <% if can?(:users, @account) %><li><%= link_to "Users", admin_account_users_path(@account) %></li><% end %>
  <% if can?(:index, @account) %><li><%= link_to "User Invitations", admin_account_user_invitations_path(@account) %></li><% end %>
  <li class="active"><%= link_to "User Invitation: #{@user_invitation}", admin_account_user_invitation_path(@account, @user_invitation) %></li>
  <% if can?(:events, @account) %><li><%= link_to "Events", admin_account_events_path(@account) %></li><% end %>
</ul>
<% end %>

<dl class="dl-horizontal">
  <dt>Invoice Number</dt>
  <dd><%= @invoice.inv_number %></dd>
  <dt>Account</dt>
  <dd><%= link_to_if can?(:show, @invoice.account), @invoice.account, admin_account_path(@invoice.account) %></dd>
  <dt>Invoiced At</dt>
  <dd><%= @invoice.invoiced_at %></dd>
  <dt>Paid At</dt>
  <dd><%= @invoice.paid_at %></dd>
  <dt>Total Amount</dt>
  <dd><%= @invoice.total_amount %></dd>
  <dt>Stripe ID</dt>
  <dd><%= @invoice.stripe_invoice_id %> <a href="https://dashboard.stripe.com/test/invoices/<%= @invoice.stripe_invoice_id  %>"><%= fa_icon 'external-link' %></a><% if @invoice.download_url %> <a href="<%= @invoice.download_url %>"><%= fa_icon 'download' %><% end %></dd>
</dl>