config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           sign_up: 'register' },
             controllers: { sessions: 'users/sessions',
                            passwords: 'users/passwords',
                            registrations: 'users/registrations',
                            unlocks: 'users/unlocks' }

  get 'users/invitation' => 'users/user_invitations#show', as: :new_user_invitation
  post 'users/invitation/accept' => 'users/user_invitations#accept', as: :accept_user_invitation
  resources :users, only: [:index, :show, :edit, :update] do
    get 'accounts' => 'users#accounts'
    get 'user_invitations' => 'users#user_invitations'
  end
  namespace :admin do
    resources :accounts, except: [:destroy] do
      resources :invoices, only: [:index]
      resources :user_invitations
      get 'cancel' => 'accounts#confirm_cancel'
      patch 'cancel' => 'accounts#cancel'
      get 'events' => 'accounts#events'
      get 'restore' => 'accounts#confirm_restore'
      patch 'restore' => 'accounts#restore'
      get 'users' => 'accounts#users'
    end
    resources :cancellation_categories, except: [:destroy] do
      resources :cancellation_reasons, except: [:destroy]
    end
    resources :invoices, only: [:index, :show]
    resources :plans do
      get 'accounts' => 'plans#accounts'
    end
    resources :users do
      get 'accounts' => 'users#accounts'
      get 'user_invitations' => 'users#user_invitations'
    end
    get 'events' => 'dashboard#events'
    get 'jobs' => 'dashboard#jobs'
    get 'user_invitations' => 'user_invitations#index'
    root to: 'dashboard#index'
  end

  get 'pricing' => 'marketing#pricing'
  get 'signup/:plan_id' => 'marketing#signup', as: :signup
  post 'signup' => 'marketing#register', as: :register

  scope ':path' do
    namespace :settings do
      resource :account, only: [:show, :edit, :update]
      resource :card, only: [:show, :edit, :update]
      resources :invoices, only: [:index, :show]
      resource :plan, only: [:show, :update, :destroy] do
        get 'cancel'
        patch 'pause'
        get ':id' => 'plans#edit', as: :edit
      end
      resources :user_permissions, except: [:create, :new]
      resources :user_invitations
      root to: 'dashboard#index'
    end
    root to: 'dashboard#index', as: :tenant_root
  end

  root to: 'marketing#index'
end

app/views/shared/_flash.html.erb
<% if Rails.env.production? %>
<%= missing_env_notice 'SECRET_KEY_BASE' %>
<% end %>
<%= missing_env_notice 'STRIPE_API_KEY' %>
<%= missing_env_notice 'STRIPE_PUBLISHABLE_KEY' %>

<% if flash.key?(:alert) %>
  <div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><%= flash[:alert] %></div>
<% end %>
<% if flash.key?(:notice) %>
  <div class="alert alert-info alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><%= flash[:notice] %></div>
<% end %>

app/views/shared/_footer.html.erb
        <div id="footer">
          <div class="container">
            <div class="row">
              <div class="col-sm-12" style="text-align: center">
                <p>Copyright 2014-15, Richard Buggy. All Rights Reserved</p>
              </div>
            </div>
          </div>
        </div>

app/views/shared/_heading.html.erb
        <div id="heading">
          <div class="container-fluid">
            <h1><%= yield :page_heading %><% if content_for? :page_sub_heading %> <small><%= yield :page_sub_heading %></small><% end %> </h1>
            <ol class="breadcrumb">
              <li><%= link_to params[:path] ? tenant_root_path : root_path do %><%= fa_icon 'home' %> Home<% end %></li>
              <%= render_breadcrumbs :tag => :li, :separator => "" %>
            </ol>
          </div>
        </div>

app/views/shared/_navbar.html.erb
<header class="main-nav">
    <%= link_to "Rails-SaaS-Template", root_path %>
    <a href="#" class="visible-xs-inline mobile-nav"><%= fa_icon 'bars' %></a>
</header>

<nav id="left-side-nav" class="hidden-xs">
   <ul class="side-nav">
<% sidebar_menu.each do |key, menu_item| %>
      <li<%if sidebar_item == key %> class="active"<% end %>>
<% if menu_item.has_key?(:submenu) %>
        <% is_expanded = sidebar_item.to_s.starts_with?(key.to_s) %>
        <%= link_to "#submenu_#{key}", { data: { toggle: 'collapse', parent: '#left-side-nav' }, aria: { expanded: is_expanded, controls: "submenu_#{key}" }, class: is_expanded ? 'has-submenu' : 'has-submenu collapsed'  } do %><% if menu_item[:icon] %><%= fa_icon menu_item[:icon], class: 'hidden-xs' %><% end %><%= menu_item[:title] %><% end %>
        <ul id="submenu_<%= key %>" class="submenu collapse <%if is_expanded %>in<% end %>">
<% menu_item[:submenu].each do |k, submenu_item| %>
          <li<%if sidebar_item == k %> class="active"<% end %>><%= link_to submenu_item[:url] do %><% if submenu_item[:icon] %><%= fa_icon submenu_item[:icon], class: 'hidden-xs' %><% end %><%= submenu_item[:title] %><% end %></li>
<% end %>
        </ul>
<% else %>
        <%= link_to menu_item[:url] do %><% if menu_item[:icon] %><%= fa_icon menu_item[:icon], class: 'hidden-xs' %><% end %><%= menu_item[:title] %><% end %>
<% end %>
      </li>
<% end %>
<% if user_signed_in? %>
      <li><%= link_to destroy_user_session_path, method: :delete do %><%= fa_icon 'sign-out', class: 'hidden-xs' %>Logout<% end %></li>
<% end %>
    </ul>
</nav>

app/views/shared/_pricing_table.html.erb
  <div class="row pricing-table">
<% plans.each do |plan| %>
    <div class="col-sm-4">
      <div class="panel panel-primary">
<% if plan.label? %>
		<div class="cnrflash">
			<div class="cnrflash-inner">
				<span class="cnrflash-label"><%= plan.label %></span>
			</div>
		</div>
<% end %>
		<div class="panel-heading"><h3><%= plan.name %></h3></div>
		<div class="panel-body">
			<div class="the-price">
				<h1><%= Money.new(plan.amount, plan.currency).format %><span class="subscript"> / <%if plan.interval_count > 1 %><%= number_with_precision(plan.interval_count, :precision => 0) %>  <% end %><%= plan.interval %></span></h1>
<% if plan.trial_period_days > 0 %>
				<small><%= plan.trial_period_days %> day FREE trial</small>
<% end %>
			</div>

			<ul class="list-group text-center" style="margin: 0">
				<li class="list-group-item"><% if plan.allow_subdomain %><%= fa_icon 'check' %><% else %><%= fa_icon 'times' %><% end %> Choose your subdomain</li>
				<li class="list-group-item"><% if plan.allow_hostname %><%= fa_icon 'check' %><% else %><%= fa_icon 'times' %><% end %> Custom domain</li>
				<li class="list-group-item"><%= fa_icon 'user' %> <%= plan.max_users %> Users</li>
			</ul>
		</div>
	    <div class="panel-footer">
<% if action == :register %>
		<%= link_to "Sign Up", signup_path(plan), class: "btn btn-lg btn-block btn-success" %>
<% else %>
<% if account.plan.id == plan.id %>
		<%= link_to "Current Plan", edit_settings_plan_path(plan), class: "btn btn-lg btn-block btn-default disabled" %>
<% else %>
		<%= link_to "Select", edit_settings_plan_path(plan), class: "btn btn-lg btn-block btn-success" %>
<% end %>
<% end %>
		</div>
      </div>
    </div>

<% end %>
  </div>