config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           sign_up: 'register' },
             controllers: { sessions: 'users/sessions',
                            passwords: 'users/passwords',
                            registrations: 'users/registrations',
                            unlocks: 'users/unlocks' }

  get 'users/invitation' => 'users/user_invitations#show', as: :new_user_invitation
  post 'users/invitation/accept' => 'users/user_invitations#accept', as: :accept_user_invitation
  resources :users, only: [:index, :show, :edit, :update] do
    get 'accounts' => 'users#accounts'
    get 'user_invitations' => 'users#user_invitations'
  end
  namespace :admin do
    resources :accounts, except: [:destroy] do
      resources :invoices, only: [:index]
      resources :user_invitations
      get 'cancel' => 'accounts#confirm_cancel'
      patch 'cancel' => 'accounts#cancel'
      get 'events' => 'accounts#events'
      get 'restore' => 'accounts#confirm_restore'
      patch 'restore' => 'accounts#restore'
      get 'users' => 'accounts#users'
    end
    resources :cancellation_categories, except: [:destroy] do
      resources :cancellation_reasons, except: [:destroy]
    end
    resources :invoices, only: [:index, :show]
    resources :plans do
      get 'accounts' => 'plans#accounts'
    end
    resources :users do
      get 'accounts' => 'users#accounts'
      get 'user_invitations' => 'users#user_invitations'
    end
    get 'events' => 'dashboard#events'
    get 'jobs' => 'dashboard#jobs'
    get 'user_invitations' => 'user_invitations#index'
    root to: 'dashboard#index'
  end

  get 'pricing' => 'marketing#pricing'
  get 'signup/:plan_id' => 'marketing#signup', as: :signup
  post 'signup' => 'marketing#register', as: :register

  scope ':path' do
    namespace :settings do
      resource :account, only: [:show, :edit, :update]
      resource :card, only: [:show, :edit, :update]
      resources :invoices, only: [:index, :show]
      resource :plan, only: [:show, :update, :destroy] do
        get 'cancel'
        patch 'pause'
        get ':id' => 'plans#edit', as: :edit
      end
      resources :user_permissions, except: [:create, :new]
      resources :user_invitations
      root to: 'dashboard#index'
    end
    root to: 'dashboard#index', as: :tenant_root
  end

  root to: 'marketing#index'
end

app/controllers/marketing_controller.rb
# Encoding: utf-8

# Copyright (c) 2014-2015, Richard Buggy <rich@buggy.id.au>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# The Marketing controller implements all of the marketing pages
class MarketingController < ApplicationController
  # Skip authentication and authorization for the marketing controller.
  # We want anonymous users to be able to access it.
  skip_before_action :authenticate_user!, only: [:pricing, :register, :signup]
  skip_authorization_check

  layout 'marketing'

  def index
    if current_user.super_admin?
      redirect_to admin_root_path
    else
      account = current_account
      account = current_user.accounts.first if account.nil?
      if account
        redirect_to tenant_root_path(path: account.to_param)
      else
        redirect_to users_path
      end
    end
  end

  def pricing
    currency = params[:currency] || 'USD'
    @plans = Plan.available_for_currency(currency)
  end

  def register
    @plan = Plan.available.find_by(id: params[:account][:plan_id])

    if @plan.nil?
      logger.debug "Select plan is not available #{params[:account][:plan_id]}"
      return redirect_to pricing_path, alert: 'Invalid plan.'
    end

    @account = Account.new(accounts_params, active: true)
    if @account.register(current_user)
      StripeAccountCreateJob.perform_later @account.id
      AppEvent.success("Created account #{@account}", @account, nil)
      logger.info { "Account '#{@account}' created - #{admin_account_url(@account)}" }
      redirect_to new_user_session_path,
                  notice: 'Success. Please log in to continue.'
    else
      logger.debug { "Account create failed #{@account.inspect}" }
      render 'signup'
    end
  end

  def signup
    @plan = Plan.available.find_by(id: params[:plan_id])
    if @plan.nil?
      logger.debug { "Plan not found #{params[:plan_id]}" }
      redirect_to pricing_path, alert: 'Invalid plan.'
    else
      @account = Account.new(plan: @plan,
                             address_country: 'us')
      @account.users.build
    end
  end

  private

  def accounts_params
    params.require(:account).permit(:address_city,
                                    :address_country,
                                    :address_line1,
                                    :address_line2,
                                    :address_state,
                                    :address_zip,
                                    :company_name,
                                    :plan_id,
                                    :card_token,
                                    users_attributes: [:first_name,
                                                       :last_name,
                                                       :email,
                                                       :password,
                                                       :password_confirmation])
  end
end

app/views/marketing/pricing.html.erb
<%
content_for(:page_title, 'Pricing')
content_for(:page_heading, 'Pricing')
%>

<%= render 'shared/pricing_table', plans: @plans, account: nil, action: :register %>

app/views/marketing/signup.html.erb
<%
content_for(:page_title, 'Sign Up')
content_for(:page_heading, 'Sign Up')
%>

<% content_for :head do %>
<% if @plan.require_card_upfront %>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<% end %>
<% end %>

<div id="stripe_errors" class="alert alert-danger" style="display:none"></div>

<%= render_errors @account %>

<%= form_for [@account], url: register_path, method: :post do |f| %>
  <%= f.hidden_field :plan_id %>
  <%= f.hidden_field :card_token %>

<% unless user_signed_in? %>
<%= f.fields_for :users do |u| %>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= u.label :first_name, class: "control-label" %>
        <%= u.text_field :first_name, class: "form-control", placeholder: "First Name" %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= u.label :last_name, class: "control-label" %>
        <%= u.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group">
        <%= u.label :email, class: "control-label" %>
        <%= u.text_field :email, class: "form-control", placeholder: "Email" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= u.label :password, class: "control-label" %>
        <%= u.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= u.label :password_confirmation, class: "control-label" %>
        <%= u.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
      </div>
    </div>
  </div>
<% end %>
<% end %>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group">
        <%= f.label :company_name, class: "control-label" %>
        <%= f.text_field :company_name, class: "form-control", placeholder: "Company Name" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group" id="account_address_line1_group" style="display: none">
        <%= f.label :address_line1, class: "control-label" %>
        <%= f.text_field :address_line1, class: "form-control", placeholder: "Street Address" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group" id="account_address_line2_group" style="display: none">
        <%= f.label :address_line2, class: "control-label" %>
        <%= f.text_field :address_line2, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group" id="account_address_city_group" style="display: none">
        <%= f.label :address_city, class: "control-label" %>
        <%= f.text_field :address_city, class: "form-control", placeholder: "City/Suburb" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group" id="account_address_state_group" style="display: none">
        <%= f.label :address_state, class: "control-label" %>
        <%= f.text_field :address_state, class: "form-control", placeholder: "State" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group" id="account_address_zip_group" style="display: none">
        <%= f.label :address_zip, class: "control-label" %>
        <%= f.text_field :address_zip, class: "form-control", placeholder: "ZIP" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group">
        <%= f.label :address_country, class: "control-label" %>
        <%= f.country_select :address_country, ["AU", "CA", "NZ", "GB", "US"], { iso_codes: true}, { class: "form-control" } %>
      </div>
    </div>
  </div>
<% if @plan.require_card_upfront %>
<% if ! (@account.card_token.nil? || @account.card_token.blank?)  %>
  <div class="form-group">
    <label class="control-label">Card</label>
    <p class="form-control-static">A valid card has been provided.</p>
  </div>
<% else %>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group" id="card_name_group">
        <label class="control-label">Card Name</label>
        <input type="text" id="cc_name" placeholder="Card Name" class="form-control" data-stripe="name">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group" id="card_number_group">
        <label class="control-label">Card Number</label>
        <div class="input-group">
          <input type="text" id="cc_number" placeholder="Card Number" class="form-control" data-stripe="number">
          <span class="input-group-addon"><%= image_tag('cards/credit_small.png', id: 'cc_image') %></span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="form-group" id="card_expiry_group">
        <label class="control-label">Expiry Date</label>
        <div class="input-group">
          <div class="col-xs-6 col-sm-6" style="padding-left: 0">
            <input type="cc_expiry_month" placeholder="MM" class="form-control" data-stripe="exp-month">
          </div>
          <div class="col-xs-6 col-sm-6" style="padding-left: 0">
            <input type="cc_expiry_year" placeholder="YYYY" class="form-control" data-stripe="exp-year">
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="form-group" id="card_cvc_group">
        <label class="control-label">CVC</label>
        <input type="text" id="cc_cvc" placeholder="CVC" class="form-control" data-stripe="cvc">
      </div>
    </div>
  </div>
<% end %>

<% end %>

  <%= f.submit "Sign Up", class: "btn btn-primary" %>
<% end %>

<% content_for :footer do %>
<% if @plan.require_card_upfront %>
<script type="text/javascript">
  // Handle the response from Stripe
  function stripeResponseHandler(status, response) {
    var form = $('form#new_account');
    if (response.error) {
      var stripe_errors = $('#stripe_errors');
      stripe_errors.text(response.error.message);
	  stripe_errors.show();
	  if (response.error.code == 'invalid_number' || response.error.code == 'incorrect_number' || response.error.code == 'card_declined') {
	    form.find('#card_number_group').addClass('has-error');
	  } else {
	    form.find('#card_number_group').removeClass('has-error');
	  }
	  if (response.error.code == 'invalid_expiry_month' || response.error.code == 'invalid_expiry_year') {
	    form.find('#card_expiry_group').addClass('has-error');
	  } else {
	    form.find('#card_expiry_group').removeClass('has-error');
	  }
	  if (response.error.code == 'invalid_cvc') {
	    form.find('#card_cvc_group').addClass('has-error');
	  } else {
	    form.find('#card_cvc_group').removeClass('has-error');
	  }
      form.find('input[type=submit]').prop('disabled', false);
    } else {
      form.find('#account_card_token').val(response.id);
      form.get(0).submit();
    }
  }

  $(function() {
    Stripe.setPublishableKey('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');

    var form = $('form.new_account');

<% unless @account.card_token? %>
    // If we have a card_token then someone previously submitted the form with a valid token so
    // we're re-using the token and didn't ask them for the credit card details this time
    form.submit(function(e) {
      e.preventDefault();
      var form = $(this);
      form.find('input[type=submit]').prop('disabled', true);
      Stripe.card.createToken(form, stripeResponseHandler);
    });
<% end %>

    // If the person selects Australia then ask for more details so we can generate a GST invoice
    form.find('#account_address_country').on("change", function(e) {
      if ($(this).val() == "au") {
        $('#account_address_line1_group').show();
        $('#account_address_line2_group').show();
        $('#account_address_city_group').show();
        $('#account_address_state_group').show();
        $('#account_address_zip_group').show();
      } else {
        $('#account_address_line1_group').hide();
        $('#account_address_line2_group').hide();
        $('#account_address_city_group').hide();
        $('#account_address_state_group').hide();
        $('#account_address_zip_group').hide();
      }
    });

    // Change the icon in the credit card number based on the credit card presented
    $('#cc_number').on("keyup", function () {
      var url = "<%= image_url("cards/credit_small.png") %>";
      switch(Stripe.card.cardType($('#cc_number').val()).toLowerCase()) {
        case "american express":
          url = "<%= image_url("cards/amex_small.png") %>";
          break;
        case "diners club":
          url = "<%= image_url("cards/diners_small.png") %>";
          break;
        case "discover":
          url = "<%= image_url("cards/discover_small.png") %>";
          break;
        case "jcb":
          url = "<%= image_url("cards/jcb_small.png") %>";
          break;
        case "mastercard":
          url = "<%= image_url("cards/mastercard_small.png") %>";
          break;
        case "visa":
          url = "<%= image_url("cards/visa_small.png") %>";
          break;
      }
      $('#cc_image').attr('src', url);
    });
  });
</script>
<% end %>
<% end %>